fix commands

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -eo pipefail
 
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
@@ -20,17 +20,14 @@ function install_version() {
 
   local tmpdir
   tmpdir=$(get_temp_dir)
-  trap 'rm -rf $tmpdir' EXIT
+  trap "rm -rf $tmpdir" EXIT
 
   (
-    set -e
     mkdir -p "$install_path/bin"
 
     echo "Installing Lucy DSL compiler v$version"
-    curl -sSfLo "$tmpdir/lucyc.tar.gz" "$bin_url" || fail "Couldn't download the lucy compiler from $bin_url"
-
-    tar -xvzf "$tmpdir/lucyc.tar.gz" "$tmpdir/lucyc"
-    mv "$tmpdir/lucyc" "$install_path/bin/"
+    curl -sSfLo "$tmpdir/lucyc.tar.gz" "$bin_url" || fail "Couldn't download the Lucy DSL compiler from $bin_url"
+    tar xzf "$tmpdir/lucyc.tar.gz" -C "$install_path/bin"
 
     chmod +x "$install_path/bin/lucyc"
   ) || (rm -rf "$install_path"; exit 1)
